name: pokedex
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.6
  flutter_riverpod: ^1.0.4
  hive_flutter: ^1.1.0
  json_annotation: ^4.6.0
  mek_data_class: ^0.1.0
  fpdart: ^0.2.0
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  json_serializable: ^6.3.1
  mek_data_class_generator: ^0.1.4
  build_runner: ^2.2.0
  flutter_native_splash: ^2.2.8
  mocktail: ^0.3.0
  flutter_gen_runner:

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400

flutter_native_splash: 
  image: "assets/images/splash_logo.png"
  color: "#3558CD"